### ISSUE TITLE
Is this repo still valid and ready to be used?

### ISSUE THREAD

**Issue by Binyang2014** [Alluxio/alluxio-csi#2]
Hi,
I want to deploy alluxio as k8s PV. Seems this repo provide an official way to do this.
But I found this repo has no been updated for a long time, and the version for alluxio-fuse is quiet old.

So is this repo still valid and ready to be used?
Thanks a lot.

**Comment by Binyang2014** [comment]
@madanadit Any comments?

**Comment by madanadit** [comment]
Hi @Binyang2014, this repo is not yet maintained. It should still be valid more the most part though.

**Comment by apc999** [comment]
this repo is contributed by community, as an experimental feature of Alluxio.
We will get back and keep it updated once this becomes priority.
